#include "StyleHtmlProvider.h"

StyleHtmlProvider::StyleHtmlProvider()
{

}

// Gets html content for CSS styles
std::string StyleHtmlProvider::getHtml()
{
    return "<style>"
           "        body {"
           "            margin: 0;"
           "        }"
           "        a {"
           "            text-decoration: none;"
           "            color: black;"
           "        }"
           "        h1 {"
           "            margin: 0;"
           "        }"
           "        ul {"
           "            list-style-type: none;"
           "            padding: 0;"
           "        }"
           "        h4 {"
           "            margin: 5px 0;"
           "        }"
           "        p {"
           "            margin: 5px 0;"
           "        }"
           "        textarea {"
           "            width: 80%;"
           "            height: 80px;"
           "        }"
           "        button {"
           "            margin: 10px 3px;"
           "        }"
           "        .banner {"
           "            background-color: #89c8f8;"
           "            padding: 40px 40px;"
           "            margin-bottom: 20px;"
           "        }"
           "        .main {"
           "            background-color:  #d9eaf7 ;"
           "            margin: 20px 40px; "
           "            padding: 15px 30px;"
           "            border: 1px;"
           "            border-style: solid;"
           "        }"
           "        .buttons {"
           "            margin: 0 40px"
           "        }"
           "        .timestamp {"
           "            padding-right: 10px;"
           "        }"
           "        .comments {"
           "            margin: 40px 0;"
           "        }"
           "        .comment {"
           "            margin: 10px 0;"
           "        }"
           "        .row {"
           "            padding: 5px 0;"
           "        }"
           "        .thread-info, .comment-info {"
           "            display: flex;"
           "            color: grey;"
           "            font-size: 12px;"
           "        }"
           "        .timestamp {"
           "            padding-right: 10px;"
           "        }"
           "        .comment-timestamp {"
           "            padding-left: 10px;"
           "        }"
           "    </style>";
}
